name: ahnaf_readhub
version: 1.0.0+1
publish_to: none
description: Project Aplikasi Perpustakaan Digital UKK RPL 2024
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  date_time_picker: ^2.1.0
  art_sweetalert: ^0.0.5
  font_awesome_flutter: ^10.6.0
  flutter_onboarding_slider: ^1.0.11
  auto_size_text: ^3.0.0
  email_validator: ^2.1.16
  cupertino_icons: ^1.0.6
  get: 4.6.6
  dio: 5.4.1
  pretty_dio_logger: ^1.3.1
  get_storage: ^2.1.1
  lottie: ^2.0.0
  google_fonts: ^6.1.0
  flutter:
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/splash/
    - assets/images/dashboard/
    - assets/images/fitur/
    - assets/images/buku/

